#!/bin/bash
mkdir -p /var/log/healthnmon
touch /var/log/healthnmon/healthnmon.log
touch /var/log/healthnmon/healthnmon-manage.log
chown -R nova:nova /var/log/healthnmon/
chmod 0700 /var/log/healthnmon
#create directory for healthmon service in var/run
mkdir -p /var/run/healthnmon

if ! grep -q sql_connection /etc/nova/nova.conf
then
      su -s /bin/sh -c 'healthnmon-manage db sync' nova
fi

service healthnmon restart
